// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToutBox.Challenge.Data;

namespace ToutBox.Challenge.Data.Migrations
{
    [DbContext(typeof(ToutboxContext))]
    partial class ToutboxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ToutBox.Challange.Core.DeliveryPrice.DeliveryServicePriceTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeliveryCalcEvent");
                });

            modelBuilder.Entity("ToutBox.Challange.Core.DeliveryPrice.DeliveryServicePriceTime", b =>
                {
                    b.OwnsMany("ToutBox.Challange.Core.DeliveryPrice.ServicePriceTime", "ServicesPriceTimes", b1 =>
                        {
                            b1.Property<Guid>("DeliveryServicePriceTimeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<decimal>("Price")
                                .HasPrecision(16, 2)
                                .HasColumnType("decimal(16,2)");

                            b1.Property<int>("Time")
                                .HasColumnType("int");

                            b1.HasKey("DeliveryServicePriceTimeId", "Id");

                            b1.ToTable("ServicePriceTimes");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryServicePriceTimeId");

                            b1.OwnsOne("ToutBox.Challange.Core.DeliveryPrice.DeliveryService", "DeliveryService", b2 =>
                                {
                                    b2.Property<Guid>("ServicePriceTimeDeliveryServicePriceTimeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("ServicePriceTimeId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .UseIdentityColumn();

                                    b2.Property<string>("ServiceCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ServiceName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ServicePriceTimeDeliveryServicePriceTimeId", "ServicePriceTimeId");

                                    b2.ToTable("ServicePriceTimes");

                                    b2.WithOwner()
                                        .HasForeignKey("ServicePriceTimeDeliveryServicePriceTimeId", "ServicePriceTimeId");
                                });

                            b1.Navigation("DeliveryService");
                        });

                    b.OwnsOne("ToutBox.Challange.Core.DeliveryPrice.ZipCode", "DestinationZipCode", b1 =>
                        {
                            b1.Property<Guid>("DeliveryServicePriceTimeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DeliveryServicePriceTimeId");

                            b1.ToTable("DeliveryCalcEvent");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryServicePriceTimeId");
                        });

                    b.OwnsOne("ToutBox.Challange.Core.DeliveryPrice.ZipCode", "SourceZipCode", b1 =>
                        {
                            b1.Property<Guid>("DeliveryServicePriceTimeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DeliveryServicePriceTimeId");

                            b1.ToTable("DeliveryCalcEvent");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryServicePriceTimeId");
                        });

                    b.Navigation("DestinationZipCode");

                    b.Navigation("ServicesPriceTimes");

                    b.Navigation("SourceZipCode");
                });
#pragma warning restore 612, 618
        }
    }
}
